[package]
name = "endpoints-inlineable"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-smithy-types = { path = "../../../rust-runtime/aws-smithy-types"}
http = "0.2.8"
url = "2.2.2"
